---
- name: Установка VPN
  hosts: all
  gather_facts: False
#  vars:
#    ansible_ssh_user: ans
#    ansible_ssh_pass: ans
  tasks:
    - name: Пробуем подключиться с ключом
      ping:
      ignore_unreachable: True
      ignore_errors: True
      register: ping_with_key_result

    - debug:
        #msg: "Testing ssh_connection_test.stderr"
        var: ping_with_key_result

    - name: Копируем ключи на хост
      block:
        - name: Ввод пароля пользователя
          pause:
            prompt: "Пароль"
            echo: yes
          register: user_password

        - name: Обновляем факты
          set_fact:
            ansible_ssh_pass: "{{ user_password.user_input }}"

        - name: debug
          debug:
            var: user_password.user_input

        - name: Добавление ключа на хост
          authorized_key:
            user: root
            key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
            state: present


      when: ping_with_key_result.unreachable is defined

    - name: Change ssh port
      pause:
        prompt: "Меняем ssh port? (yes/no): "
      register: change_ssh_port_response

    - name: Check user choice
      set_fact:
        change_ssh_port: "{{ change_ssh_port_response.user_input | lower == 'yes' }}"
      when: change_ssh_port_response.user_input | lower in ['yes', 'no']

    - name: debug
      gebug:
        msg: "{{ ansible_port }} and {{ change_ssh_port_response.user_input }}"
  





