---
- name: Установка VPN
  hosts: all
  gather_facts: False
#  vars:
#    ansible_ssh_user: ans
#    ansible_ssh_pass: ans
  vars_prompt:
    - name: connect_ssh_port
      prompt: "Укажите SSH порт для подключения"
      default: "22"
      private: false



  tasks:
    - name: Пробуем подключиться с ключом
      ping:
      ignore_unreachable: True
      ignore_errors: True
      register: ping_with_key_result

    - debug:
        #msg: "Testing ssh_connection_test.stderr"
        var: ping_with_key_result

    - name: Копируем ключи на хост
      block:
        - name: Ввод пароля пользователя
          pause:
            prompt: "Пароль"
            echo: yes
          register: user_password

        - name: Обновляем факты
          set_fact:
            ansible_ssh_pass: "{{ user_password.user_input }}"

        - debug:
            var: user_password.user_input

        - name: Добавление ключа на хост
          authorized_key:
            user: root
            key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
            state: present


      when: ping_with_key_result.unreachable is defined

    - name: Change ssh port query
      pause:
        prompt: "Меняем ssh port? (y/n)"
      register: change_ssh_port_response

    - name: Check user choice
      set_fact:
        change_ssh_port: "{{ change_ssh_port_response.user_input | lower == 'y' }}"
      when: change_ssh_port_response.user_input | lower in ['y', 'n']

    - debug:
        #msg: "{{ ansible_port }} and {{ change_ssh_port_response.user_input }}"
      when: change_ssh_port

    - name: Change SSH port
      block:

        - name: Enter new SSH port
          pause:
            prompt: "Новый SSH порт: "
          register: new_port_response

        - name: Update SSH Port in sshd_config
          lineinfile:
            dest: "/etc/ssh/sshd_config"
            regexp: "^Port"
            line: "Port {{ configured_port }}"
          notify: "Restart sshd"


        - name: Меняем порт в inventory
          delegate_to: localhost
          replace:
            path: "{{ inventory_file }}"
            regexp: "(^test.*ansible_port=)\\d+(.*)$"
            replace: "\\g<1>{{ new_port_response.user_input }}\\2"
            #backup: True

        - debug:
            msg: "{{ inventory_file }} и {{ inventory_hostname }} и {{ ansible_port }}"

      when: change_ssh_port












  handlers:
    - name: Restart sshd
      service:
        name: sshd
        state: restarted



















