---
- name: Check OS using Facts
  hosts: all
  gather_facts: yes
  
  tasks:
    - name: Display OS Facts
      debug:
        var: ansible_distribution
        
    - name: Display OS Version
      debug:
        var: ansible_distribution_version
      
    - name: Check if Debian
      when: ansible_distribution == 'Debian'
      debug:
        msg: "This is a Debian system."
