---
- name: Установка VPN
  hosts: all
  gather_facts: False
#  vars:
#    ansible_ssh_user: ans
#    ansible_ssh_pass: ans
  tasks:
    - name: Ввод пароля пользователя
      pause:
        prompt: "Пароль"
        echo: yes
      register: user_password

    - name: Обновляем факты
      set_fact:
        ansible_ssh_pass: "{{ user_password.user_input }}"

#    - name: Сбор фактов о системе
#      ansible.builtin.setup:

    - name: ping
      ping:

